#lang info
(define collection "htmx")
(define deps '("base" "rackunit-lib"))
(define build-deps '("scribble-lib" "racket-doc"))
(define scribblings '(("scribblings/htmx.scrbl" ())
                      ("scribblings/htmx-es.scrbl" ())))
(define pkg-desc "DSL funcional en Racket para generar atributos HTMX y X-expressions mediante composición pura")
(define version "1.0")
(define pkg-authors '(javier))
(define license '(Apache-2.0 OR MIT))
